services:
    dcim:
        name: dcim
        description: Data Center Infrastructure Management
        resources:
            device type:
                name: device type
                plural: device types
                description: A device type represents a particular manufacturer's model of device. For example, N9K-C9396PX or PowerEdge R630.
                attributes:
                    id:
                        name: ID
                        description: The unique numeric ID of the device type.
                        type: int64
                        key: true
                        nullable: true
                    model:
                        name: Model
                        description: The model name of the device type.
                        value: Test Device Type
                        type: string
                        maxLength: 100
                        minLength: 1
                        nullable: true
                    part number:
                        name: Part Number
                        description: The part number associated with the device type.
                        type: string
                        maxLength: 50
                    slug:
                        name: Slug
                        description: A unique slug identifier for the device type.
                        value: test-device-type
                        type: string
                        maxLength: 100
                        minLength: 1
                        pattern: ^[-a-zA-Z0-9_]+$
                        nullable: true
                associations:
                    manufacturer:
                        name: Manufacturer
                        description: The device type's manufacturer.
                        type: manufacturer
                        min: 1
                        max: 1
                        nullable: true
                writeableModel: WritableDeviceType
                readableModel: DeviceType
            manufacturer:
                name: manufacturer
                plural: manufacturers
                description: A manufacturer represents a company which produces hardware devices; for example, Juniper or Dell.
                attributes:
                    id:
                        name: ID
                        description: The unique numeric ID of the manufacturer.
                        type: int64
                        key: true
                        nullable: true
                    name:
                        name: Name
                        description: The name of the manufacturer.
                        value: Test Manufacturer
                        type: string
                        maxLength: 100
                        minLength: 1
                        nullable: true
                    slug:
                        name: Slug
                        description: A unique slug identifier for the manufacturer.
                        value: test-manufacturer
                        type: string
                        maxLength: 100
                        minLength: 1
                        pattern: ^[-a-zA-Z0-9_]+$
                        nullable: true
                writeableModel: Manufacturer
                readableModel: Manufacturer
            site:
                name: site
                plural: sites
                description: A site represents a logical grouping of devices, typically by physical location or purpose. For example, a site might be a data center, an office building, or a distributed network of servers.
                attributes:
                    id:
                        name: ID
                        description: The unique numeric ID of the site.
                        type: int64
                        key: true
                        nullable: true
                    name:
                        name: Name
                        description: The name of the site.
                        value: Test Site
                        type: string
                        maxLength: 100
                        minLength: 1
                        nullable: true
                    slug:
                        name: Slug
                        description: A unique slug identifier for the site.
                        value: test-site
                        type: string
                        maxLength: 100
                        minLength: 1
                        pattern: ^[-a-zA-Z0-9_]+$
                        nullable: true
                associations:
                    tenant:
                        name: Tenant
                        description: The tenant to which this site is assigned.
                        type: site
                        max: 1
                        nullable: true
                writeableModel: WritableSite
                readableModel: Site
    ipam:
        name: ipam
        description: IP Address Management
        resources:
            prefix:
                name: prefix
                plural: prefixes
                description: A prefix represents an assignable range of IP addresses
                attributes:
                    id:
                        name: ID
                        description: The unique numeric ID of the prefix.
                        value: "123"
                        type: int64
                        key: true
                        nullable: true
                    prefix:
                        name: Prefix
                        description: The prefix address in CIDR notation.
                        value: 10.0.0.0/24
                        type: string
                        maxLength: 43
                        minLength: 1
                        pattern: ^[0-9a-fA-F.:]+/[0-9]+$
                        nullable: true
                associations:
                    role:
                        name: Role
                        description: The role to which this prefix is assigned.
                        type: role
                        max: 1
                        nullable: true
                    site:
                        name: Site
                        description: The site to which this prefix is assigned.
                        type: site
                        max: 1
                        nullable: true
                    tenant:
                        name: Tenant
                        description: The tenant to which this prefix is assigned.
                        type: tenant
                        max: 1
                        nullable: true
                writeableModel: WritablePrefix
                readableModel: Prefix
            role:
                name: role
                plural: roles
                description: A role indicates the function of a prefix or VLAN. For example, you might define Data, Voice, and Security roles. A role can be assigned to multiple prefixes and VLANs.
                attributes:
                    id:
                        name: ID
                        description: The unique numeric ID of the role.
                        type: int64
                        key: true
                        nullable: true
                    name:
                        name: Name
                        description: The name of the role.
                        value: Test Role
                        type: string
                        maxLength: 100
                        minLength: 1
                        nullable: true
                    slug:
                        name: Slug
                        description: A unique slug identifier for the role.
                        value: test-role
                        type: string
                        maxLength: 100
                        minLength: 1
                        pattern: ^[-a-zA-Z0-9_]+$
                        nullable: true
                writeableModel: Role
                readableModel: Role
    tenancy:
        name: tenancy
        description: Tenancy provides a framework for logically isolating objects within NetBox.
        resources:
            tenant:
                name: tenant
                plural: tenants
                description: A tenant represents a discrete grouping of resources used for administrative purposes.
                attributes:
                    id:
                        name: ID
                        description: The unique numeric ID of the tenant.
                        type: int64
                        key: true
                        nullable: true
                    name:
                        name: Name
                        description: The name of the tenant.
                        value: Test Tenant
                        type: string
                        maxLength: 100
                        minLength: 1
                        nullable: true
                    slug:
                        name: Slug
                        description: A unique slug identifier for the tenant.
                        value: test-tenant
                        type: string
                        maxLength: 100
                        minLength: 1
                        pattern: ^[-a-zA-Z0-9_]+$
                        nullable: true
                associations:
                    group:
                        name: Group
                        description: The tenant group this tenant belongs to.
                        type: tenant_group
                        max: 1
                        nullable: true
                writeableModel: WritableTenant
                readableModel: Tenant
            tenant_group:
                name: tenant group
                plural: tenant groups
                description: A tenant group represents a collection of tenants.
                attributes:
                    id:
                        name: ID
                        description: The unique numeric ID of the tenant group.
                        type: int64
                        key: true
                        nullable: true
                    name:
                        name: Name
                        description: The name of the tenant group.
                        value: Test Tenant Group
                        type: string
                        maxLength: 100
                        minLength: 1
                        nullable: true
                    slug:
                        name: Slug
                        description: A unique slug identifier for the tenant group.
                        value: test-tenant-group
                        type: string
                        maxLength: 100
                        minLength: 1
                        pattern: ^[-a-zA-Z0-9_]+$
                        nullable: true
                writeableModel: WritableTenantGroup
                readableModel: TenantGroup
